[package]
name = "hexbuffer-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hb-cli"
path = "src/bin/hb_cli.rs"

[[bin]]
name = "hexbuffer-cli"
path = "src/main.rs"

[[bin]]
name = "arch-cli"
path = "src/bin/arch_cli.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
inquire = "0.7"
minijinja = "2.7"
anyhow = "1.0"
tokio = { version = "1.43", features = ["full"] }
heck = "0.5"
